FORMAT: 1A
HOST: https://api.hubcash.com/v1

# API v1.0 - Documentation
First of all, thanks for using our API. This documentation will guide you how to implement
 your application to take advantage of our payment, delivery and fraud control solutions.

<br/>

## Authorization
To do so, we need use keys in *http headers* for all requests as specified below:

```http
X-Hubcash-Code: string
X-Hubcash-Token: string
```

::: note
## Keys
If you don't have these keys yet, you can can gain access following the links:

* [Production](#) keys to your production environment;
* [Development](#) keys to your development environment and testing;
:::

> "For both environments you can use the default endpoint."

<br/>

## Support
[Contact support team](#), you can always contact us to get more information.

<br/>


# Data Structures

## PostCardData (object)
+ Brand: Visa (required) - Card brand name
+ HolderName: Maria da Silva (required) - Holder name
+ Document: 223.112.333.112-22 (required) - Document of the holder
+ Phone: 93 912323322 (optional) - Optional phone of the holder
+ ExpMonth: 03 (required) - Card expiration month (mm)
+ ExpYear: 2022 (required) - Card expiration year (yyyy)
+ Number: 5162321366555222331234 (required) - (Requests) Card number
+ SecurityCode: 233 (required) - Card security code

## PutCardData (object)
+ Brand: Visa (required) - Card brand name
+ HolderName: Maria da Silva (required) - Holder name
+ Document: 223.112.333.112-22 (required) - Document of the holder
+ Phone: 93 912323322 (optional) - Optional phone of the holder
+ ExpMonth: 03 (required) - Card expiration month (mm)
+ ExpYear: 2022 (required) - Card expiration year (yyyy)

## ViewCardData (object)
+ CardId: 58c040b32d8baf18526217f5 (optional) - Unique identifier
+ Brand: Visa (required) - Card brand name
+ HolderName: Maria da Silva (required) - Holder name
+ Document: 223.112.333.112-22 (required) - Document of the holder
+ Phone: 93 912323322 (optional) - Optional phone of the holder
+ ExpMonth: 03 (required) - Card expiration month (mm)
+ ExpYear: 2022 (required) - Card expiration year (yyyy)
+ LastDigits: 1234 (optional) - Last digits of the cards
+ DateUpdated: DateTime (optional) -  Date updated
+ DateAdded: DateTime (optional) -  Date added

## CardList (array)
+ (ViewCardData) - Cards


# Group Cards
Credit and debit cards can be saved to be used by the consumer recurrently transactions.

## Card detail [/cards/{CardId}]

+ Parameters
    + CardId - Identifier

### Details [GET]

+ Request example (application/json)

    + Headers

            X-Hubcash-Code: <code>
            X-Hubcash-Token: <token>

+ Response 200 (application/json)

    + Attributes (object)
        + Card (ViewCardData)

### Edit [PUT]

+ Request example (application/json)

    + Headers

            X-Hubcash-Code: <code>
            X-Hubcash-Token: <token>

    + Attributes (object)
        + Card (PutCardData)

+ Response 200 (application/json)

    + Attributes (object)
        + Card (ViewCardData)

### Delete [DELETE]

+ Request example (application/json)

    + Headers

            X-Hubcash-Code: <code>
            X-Hubcash-Token: <token>

+ Response 200 (application/json)

    + Attributes (object)
        + Success (string)


## Cards by document [/cards/document/{document}{?pg}]
Get a list of cards by consumer document.

+ Parameters
    + document - Document of the consumer
    + pg: `1` (number, optional) - Page number

### By document [GET]

+ Request example (application/json)

    + Headers

            X-Hubcash-Code: <code>
            X-Hubcash-Token: <token>

+ Response 200 (application/json)

    + Attributes (object)
        + Cards (CardList)
        + Pages (number)


## Create New Card [/cards]

### Create [POST]

+ Request example (application/json)

    + Headers

            X-Hubcash-Code: <code>
            X-Hubcash-Token: <token>

    + Attributes (object)
        + Card (PostCardData)

+ Response 200 (application/json)

    + Attributes (object)
        + Card (ViewCardData)
